#!/usr/bin/env php
<?php
require dirname(__DIR__) . '/vendor/autoload.php';
use CarlosIO\WhatsApp\Command\SendCommand;
/*
use CarlosIO\WhatsApp\Command\ListenCommand;
use CarlosIO\WhatsApp\Command\InteractiveConversationCommand;
use CarlosIO\WhatsApp\Command\ChangeStatusCommand;
*/
use Symfony\Component\Console\Application;
$application = new Application();
$application->add(new SendCommand);
/*
$sender="491788255224";
$imei="354735076385726";
$application->add(new ChangeStatusCommand);
*/
$application->run();
